coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
    patch: off

comment:
  layout: "diff, files"
  require_changes: false
  require_base: no
  require_head: no
