import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val activity_compose: String = "androidx.activity:activity-compose:_"

    public const val core_testing: String = "androidx.arch.core:core-testing:_"

    public const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    public const val foundation: String = "androidx.compose.foundation:foundation:_"

    public const val material3_window_size_class: String =
            "androidx.compose.material3:material3-window-size-class:_"

    public const val androidx_compose_material_material: String =
            "androidx.compose.material:material:_"

    public const val material_icons_extended: String =
            "androidx.compose.material:material-icons-extended:_"

    public const val runtime_livedata: String = "androidx.compose.runtime:runtime-livedata:_"

    public const val ui: String = "androidx.compose.ui:ui:_"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    public const val ui_tooling_preview: String = "androidx.compose.ui:ui-tooling-preview:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val customview_poolingcontainer: String =
            "androidx.customview:customview-poolingcontainer:_"

    public const val viewbinding: String = "androidx.databinding:viewbinding:_"

    public const val hilt_compiler: String = "androidx.hilt:hilt-compiler:_"

    public const val lifecycle_livedata_core_ktx: String =
            "androidx.lifecycle:lifecycle-livedata-core-ktx:_"

    public const val lifecycle_viewmodel_compose: String =
            "androidx.lifecycle:lifecycle-viewmodel-compose:_"

    public const val lifecycle_viewmodel_savedstate: String =
            "androidx.lifecycle:lifecycle-viewmodel-savedstate:_"

    public const val androidx_test_ext_junit: String = "androidx.test.ext:junit:_"

    public const val androidx_test_core: String = "androidx.test:core:_"

    public const val layoutlib_native_macarm: String =
            "app.cash.paparazzi:layoutlib-native-macarm:_"

    public const val paparazzi: String = "app.cash.paparazzi:paparazzi:_"

    public const val paparazzi_gradle_plugin: String =
            "app.cash.paparazzi:paparazzi-gradle-plugin:_"

    public const val showkase: String = "com.airbnb.android:showkase:_"

    public const val showkase_processor: String = "com.airbnb.android:showkase-processor:_"

    public const val showkase_screenshot_testing: String =
            "com.airbnb.android:showkase-screenshot-testing:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val accompanist_systemuicontroller: String =
            "com.google.accompanist:accompanist-systemuicontroller:_"

    public const val com_google_android_material_material: String =
            "com.google.android.material:material:_"

    public const val hilt_android: String = "com.google.dagger:hilt-android:_"

    public const val hilt_android_compiler: String = "com.google.dagger:hilt-android-compiler:_"

    public const val hilt_android_gradle_plugin: String =
            "com.google.dagger:hilt-android-gradle-plugin:_"

    public const val hilt_android_testing: String = "com.google.dagger:hilt-android-testing:_"

    public const val test_parameter_injector: String =
            "com.google.testparameterinjector:test-parameter-injector:_"

    public const val truth: String = "com.google.truth:truth:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val detekt_formatting: String = "io.gitlab.arturbosch.detekt:detekt-formatting:_"

    public const val detekt_gradle_plugin: String =
            "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val junit_junit: String = "junit:junit:_"

    public const val org_jacoco_agent: String = "org.jacoco:org.jacoco.agent:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val org_jacoco_core: String = "org.jacoco:org.jacoco.core:_"

    public const val kotlin_annotation_processing_gradle: String =
            "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val robolectric: String = "org.robolectric:robolectric:_"
}
