import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val io_gitlab_arturbosch_detekt: String = "1.10.0"

    const val org_jetbrains_kotlin: String = "1.3.72"

    const val androidx_lifecycle: String = "2.2.0"

    const val com_google_dagger: String = "2.28.1-alpha"

    const val androidx_hilt: String = "1.0.0-alpha01"

    const val com_android_tools_build_gradle: String = "4.2.0"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val androidx_test_core: String = "1.2.0"

    const val junit_junit: String = "4.13"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val gradle_android_junit_jacoco_plugin: String = "0.16.0"

    const val constraintlayout: String = "1.1.3"

    const val espresso_core: String = "3.2.0"

    const val core_testing: String = "2.1.0"

    const val fragment_ktx: String = "1.2.5"

    const val lint_gradle: String = "27.2.0"

    const val robolectric: String = "4.3.1"

    const val viewbinding: String = "4.2.0"

    const val appcompat: String = "1.1.0"

    const val core_ktx: String = "1.3.0"

    const val material: String = "1.1.0"

    const val aapt2: String = "4.2.0"

    const val mockk: String = "1.10.0"

    const val truth: String = "1.0.1"

    /**
     * Current version: "6.5-rc-1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.7.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
